Fix null check

diff --git a/ci/release/Jenkinsfile b/ci/release/Jenkinsfile
--- a/ci/release/Jenkinsfile
+++ b/ci/release/Jenkinsfile
@@ -187,19 +187,16 @@ EOF
                         curl -s -H "Authorization: token $GIT_TOKEN" -X POST https://api.github.com/repos/Talend/data-quality/pulls -d @pull-request.json -o result.json
                         """
                         script {
-                            pr_link = sh(returnStdout: true, script: "cat result.json | jq '.html_url' | sed 's/\"//g'")
+                            pr_link = sh(returnStdout: true, script: "cat result.json | jq '.html_url' | sed 's/\"//g'").trim()
                             echo "PR Link = $pr_link"
+                            if (pr_link != "null") {
+                                echo "The pull request url: $pr_link\nPlease review and merge it from Github Web UI."
+
+                            } else {
+                                echo "Failed to create pull request, details as below:"
+                                sh(script: 'cat result.json; exit 1')
+                            }
                         }
-                        sh """#! /bin/sh
-                        if [ ! -n "$pr_link" ]
-                        then
-                            echo -e "The pull request url: $pr_link\\nPlease review and merge it from Github Web UI."
-                        else
-                            echo "Failed to create pull request, details as below:"
-                            cat result.json
-                            exit 1
-                        fi
-                       """
                     }
                 }
             }
